service: commudle-admin

plugins:
  - serverless-apigw-binary
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  timeout: 10
  region: api-south-1

package:
  exclude:
    - ../**
  include:
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
    - "projects/commudle-admin/lambda.js"


custom:
  apigwBinary:
    types:
      - "*/*"

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
